version: '3'

services:
  mariadb:
    image: mariadb
    container_name: test-smallprod-models-maria
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
  mysql:
    image: mysql
    container_name: test-smallprod-models-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret123
      MYSQL_DATABASE: test
    ports:
      - 3307:3306
  postgres:
    image: postgres
    container_name: test-smallprod-models-postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: test
    ports:
      - 5432:5432
  # mssql:
  #   image: mcr.microsoft.com/mssql/server
  #   container_name: test-smallprod-models-mssql
  #   environment:
  #     ACCEPT_EULA: 'Y'
  #     SA_PASSWORD: secret123
  #   ports:
  #     - 1433:1433
